/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.SinhVienController;
import database.Connect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.SinhVien;

/**
 *
 * @author Admin
 */
public class SinhVienLayOut extends javax.swing.JFrame {

    /**
     * Creates new form ThongBaoSinhVienLayOut
     */
    Connect conn = new Connect();
    String ngaysinh, quequan, email;
    DangNhapLayOut dn = new DangNhapLayOut();

    public SinhVienLayOut() {
        setSize(1000, 1000);
        initComponents();
        GetDataSinhVien();
    }

    void getTxt() {
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        ngaysinh = df.format(jdNgaySinh.getDate());
        quequan = txtQueQuan.getText();
        email = txtEmail.getText();
    }

    void GetDataSinhVien() {
        ResultSet resultset = conn.queryData("select * from sinhvien where masv = " + dn.tk);
        try {
            if (resultset.next()) {
                SinhVien sv = new SinhVien(resultset.getString("masv"), resultset.getString("hoten"), resultset.getString("ngaysinh"), resultset.getString("gioitinh"), resultset.getString("quequan"), resultset.getString("sdt"), resultset.getString("gmail"), resultset.getString("malop"), String.valueOf(resultset.getInt("congno")));
                lbtensv.setText(sv.getHoten());
                lbmasv.setText(sv.getMasv());
                lbmalop.setText(sv.getMalop());
                lbquequan.setText(sv.getQuequan());
                lbngaysinh.setText(sv.getNgaysinh());
                lbcongno.setText(sv.getCongno());
                lbemail.setText(sv.getGmail());
            }
        } catch (SQLException ex) {
            Logger.getLogger(SinhVienController.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }

        ResultSet rs = conn.queryData("select thongbao from sohocphi where hocky = (select max(hocky) from sohocphi)");
        try {
            if (rs.next()) {
                txtaThongbao.setText(rs.getString("thongbao"));
            } else {
                txtaThongbao.setText("Chưa có thông báo nào");
            }
        } catch (SQLException ex) {
            Logger.getLogger(SinhVienLayOut.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaThongbao = new javax.swing.JTextArea();
        txtQueQuan = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnDangKyMon = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jdNgaySinh = new com.toedter.calendar.JDateChooser();
        lbquequan = new javax.swing.JLabel();
        lbmasv = new javax.swing.JLabel();
        lbtensv = new javax.swing.JLabel();
        lbngaysinh = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        lbmalop = new javax.swing.JLabel();
        lbcongno = new javax.swing.JLabel();
        btnReload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin cá nhân sinh viên");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel2.setText("Mã sinh viên : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 85, -1, -1));

        jLabel3.setText("Tên sinh viên : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 123, -1, -1));

        jLabel4.setText("Ngày sinh");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 161, -1, -1));

        jLabel5.setText("Quê quán : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 199, -1, -1));

        jLabel6.setText("Email : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 237, -1, -1));

        jLabel7.setText("Mã lớp : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 275, -1, -1));

        jLabel8.setText("Công nợ :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 313, -1, -1));

        jLabel9.setText("Thông báo từ nhà trường : ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        txtaThongbao.setColumns(20);
        txtaThongbao.setRows(5);
        jScrollPane1.setViewportView(txtaThongbao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 390, -1));
        getContentPane().add(txtQueQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 196, 130, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 234, 130, -1));

        btnDangKyMon.setText("Đăng ký môn học");
        btnDangKyMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyMonActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangKyMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 329, 170, 30));

        btnSua.setText("Cập nhật thông tin");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 274, 170, 30));

        jdNgaySinh.setDateFormatString("dd/MM/yyyy\n");
        getContentPane().add(jdNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 155, 160, -1));

        lbquequan.setText("                      ");
        getContentPane().add(lbquequan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 199, 121, -1));

        lbmasv.setText("                      ");
        getContentPane().add(lbmasv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 85, 121, -1));

        lbtensv.setText("                      ");
        getContentPane().add(lbtensv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 123, 121, -1));

        lbngaysinh.setText("                      ");
        getContentPane().add(lbngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 161, 121, -1));

        lbemail.setText("                      ");
        getContentPane().add(lbemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 237, 121, -1));

        lbmalop.setText("                      ");
        getContentPane().add(lbmalop, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 275, 121, -1));

        lbcongno.setText("                      ");
        getContentPane().add(lbcongno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 313, 121, -1));

        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });
        getContentPane().add(btnReload, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        getTxt();
        String sql = "update sinhvien set ngaysinh = '" + ngaysinh + "', quequan = '" + quequan + "', gmail = '" + email + "' where masv = " + (dn.tk);
        int check = conn.UpdateData(sql);
        if (check == 1) {
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thành công");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thất bại");
        }
        GetDataSinhVien();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnDangKyMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyMonActionPerformed
        DangKyMonHocLayOut dangky = new DangKyMonHocLayOut();
        dangky.setVisible(true);
    }//GEN-LAST:event_btnDangKyMonActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        GetDataSinhVien();
    }//GEN-LAST:event_btnReloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienLayOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienLayOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienLayOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienLayOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVienLayOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKyMon;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnSua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdNgaySinh;
    private javax.swing.JLabel lbcongno;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbmalop;
    private javax.swing.JLabel lbmasv;
    private javax.swing.JLabel lbngaysinh;
    private javax.swing.JLabel lbquequan;
    private javax.swing.JLabel lbtensv;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextArea txtaThongbao;
    // End of variables declaration//GEN-END:variables
}
