/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import controller.SinhVienController;
import database.Connect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.SinhVien;
import view.DangNhap;

/**
 *
 * @author Admin
 */
public class ThongBaoSinhVienLayOut extends javax.swing.JFrame {

    /**
     * Creates new form ThongBaoSinhVienLayOut
     */
    Connect conn = new Connect();

    public ThongBaoSinhVienLayOut() {
        initComponents();
        GetDataSinhVien();
    }

    void GetDataSinhVien() {
        DangNhap dn = new DangNhap();
        ResultSet resultset = conn.queryData("select * from sinhvien where masv = " + dn.tk);
        try {
            if (resultset.next()) {
                SinhVien sv = new SinhVien(resultset.getString("masv"), resultset.getString("hoten"), resultset.getString("ngaysinh"), resultset.getString("gioitinh"), resultset.getString("quequan"), resultset.getString("sdt"), resultset.getString("gmail"), resultset.getString("malop"), resultset.getInt("congno") + "");
                txtmasv.setText(sv.getMasv());
                txtten.setText(sv.getHoten());
                txtngaysinh.setText(sv.getNgaysinh());
                txtemail.setText(sv.getGmail());
                txtmalop.setText(sv.getMalop());
                txtque.setText(sv.getQuequan());
                txtcongno.setText(sv.getCongno());
            }
        } catch (SQLException ex) {
            Logger.getLogger(SinhVienController.class.getName()).log(Level.SEVERE, null, ex);
        }

        ResultSet rs = conn.queryData("select thongbao from sohocphi where hocky = (select max(hocky) from sohocphi)");
        try {
            if (rs.next()) {
                txtaThongbao.setText(rs.getString("thongbao"));
            } else {
                txtaThongbao.setText("Chưa có thông báo nào");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThongBaoSinhVienLayOut.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmasv = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        txtque = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtmalop = new javax.swing.JTextField();
        txtcongno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaThongbao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Thông báo dành cho sinh viên");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setText("Mã sinh viên : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 85, -1, -1));

        jLabel3.setText("Tên sinh viên : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 123, -1, -1));

        jLabel4.setText("Ngày sinh");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 161, -1, -1));

        jLabel5.setText("Quê quán : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 199, -1, -1));

        jLabel6.setText("Email : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 237, -1, -1));

        jLabel7.setText("Mã lớp : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 275, -1, -1));

        jLabel8.setText("Công nợ :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 313, -1, -1));
        getContentPane().add(txtmasv, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 82, 120, -1));
        getContentPane().add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 120, 120, -1));
        getContentPane().add(txtngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 158, 120, -1));
        getContentPane().add(txtque, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 196, 120, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 234, 120, -1));
        getContentPane().add(txtmalop, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 272, 120, -1));
        getContentPane().add(txtcongno, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 310, 120, -1));

        jLabel9.setText("Thông báo từ nhà trường : ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        txtaThongbao.setColumns(20);
        txtaThongbao.setRows(5);
        jScrollPane1.setViewportView(txtaThongbao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 390, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongBaoSinhVienLayOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongBaoSinhVienLayOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongBaoSinhVienLayOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongBaoSinhVienLayOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongBaoSinhVienLayOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtaThongbao;
    private javax.swing.JTextField txtcongno;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmalop;
    private javax.swing.JTextField txtmasv;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtque;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
}
